// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network/aviatrix/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PlaneMeta struct {
	Experience uint64 `protobuf:"varint,3,opt,name=experience,proto3" json:"experience,omitempty"`
}

func (m *PlaneMeta) Reset()         { *m = PlaneMeta{} }
func (m *PlaneMeta) String() string { return proto.CompactTextString(m) }
func (*PlaneMeta) ProtoMessage()    {}
func (*PlaneMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{0}
}
func (m *PlaneMeta) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PlaneMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PlaneMeta.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PlaneMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaneMeta.Merge(m, src)
}
func (m *PlaneMeta) XXX_Size() int {
	return m.Size()
}
func (m *PlaneMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaneMeta.DiscardUnknown(m)
}

var xxx_messageInfo_PlaneMeta proto.InternalMessageInfo

func (m *PlaneMeta) GetExperience() uint64 {
	if m != nil {
		return m.Experience
	}
	return 0
}

type Plane struct {
	Id    string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Owner string     `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Meta  *PlaneMeta `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (m *Plane) Reset()         { *m = Plane{} }
func (m *Plane) String() string { return proto.CompactTextString(m) }
func (*Plane) ProtoMessage()    {}
func (*Plane) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{1}
}
func (m *Plane) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Plane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Plane.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Plane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Plane.Merge(m, src)
}
func (m *Plane) XXX_Size() int {
	return m.Size()
}
func (m *Plane) XXX_DiscardUnknown() {
	xxx_messageInfo_Plane.DiscardUnknown(m)
}

var xxx_messageInfo_Plane proto.InternalMessageInfo

func (m *Plane) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Plane) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Plane) GetMeta() *PlaneMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MsgCreatePlane struct {
	Id         string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Supervisor string     `protobuf:"bytes,2,opt,name=supervisor,proto3" json:"supervisor,omitempty"`
	Owner      string     `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Meta       *PlaneMeta `protobuf:"bytes,4,opt,name=meta,proto3" json:"meta,omitempty"`
}

func (m *MsgCreatePlane) Reset()         { *m = MsgCreatePlane{} }
func (m *MsgCreatePlane) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePlane) ProtoMessage()    {}
func (*MsgCreatePlane) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{2}
}
func (m *MsgCreatePlane) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePlane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePlane.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePlane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePlane.Merge(m, src)
}
func (m *MsgCreatePlane) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePlane) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePlane.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePlane proto.InternalMessageInfo

func (m *MsgCreatePlane) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgCreatePlane) GetSupervisor() string {
	if m != nil {
		return m.Supervisor
	}
	return ""
}

func (m *MsgCreatePlane) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *MsgCreatePlane) GetMeta() *PlaneMeta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MsgCreatePlaneResponse struct {
}

func (m *MsgCreatePlaneResponse) Reset()         { *m = MsgCreatePlaneResponse{} }
func (m *MsgCreatePlaneResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreatePlaneResponse) ProtoMessage()    {}
func (*MsgCreatePlaneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{3}
}
func (m *MsgCreatePlaneResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreatePlaneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreatePlaneResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreatePlaneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreatePlaneResponse.Merge(m, src)
}
func (m *MsgCreatePlaneResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreatePlaneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreatePlaneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreatePlaneResponse proto.InternalMessageInfo

type MsgUpdatePlaneExperience struct {
	Supervisor string `protobuf:"bytes,1,opt,name=supervisor,proto3" json:"supervisor,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Amount     uint64 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgUpdatePlaneExperience) Reset()         { *m = MsgUpdatePlaneExperience{} }
func (m *MsgUpdatePlaneExperience) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePlaneExperience) ProtoMessage()    {}
func (*MsgUpdatePlaneExperience) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{4}
}
func (m *MsgUpdatePlaneExperience) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePlaneExperience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePlaneExperience.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePlaneExperience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePlaneExperience.Merge(m, src)
}
func (m *MsgUpdatePlaneExperience) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePlaneExperience) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePlaneExperience.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePlaneExperience proto.InternalMessageInfo

func (m *MsgUpdatePlaneExperience) GetSupervisor() string {
	if m != nil {
		return m.Supervisor
	}
	return ""
}

func (m *MsgUpdatePlaneExperience) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgUpdatePlaneExperience) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MsgUpdatePlaneExperienceResponse struct {
}

func (m *MsgUpdatePlaneExperienceResponse) Reset()         { *m = MsgUpdatePlaneExperienceResponse{} }
func (m *MsgUpdatePlaneExperienceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdatePlaneExperienceResponse) ProtoMessage()    {}
func (*MsgUpdatePlaneExperienceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{5}
}
func (m *MsgUpdatePlaneExperienceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdatePlaneExperienceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdatePlaneExperienceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdatePlaneExperienceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdatePlaneExperienceResponse.Merge(m, src)
}
func (m *MsgUpdatePlaneExperienceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdatePlaneExperienceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdatePlaneExperienceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdatePlaneExperienceResponse proto.InternalMessageInfo

type MsgAdjustPlaneExperience struct {
	Supervisor string `protobuf:"bytes,1,opt,name=supervisor,proto3" json:"supervisor,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Amount     int64  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *MsgAdjustPlaneExperience) Reset()         { *m = MsgAdjustPlaneExperience{} }
func (m *MsgAdjustPlaneExperience) String() string { return proto.CompactTextString(m) }
func (*MsgAdjustPlaneExperience) ProtoMessage()    {}
func (*MsgAdjustPlaneExperience) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{6}
}
func (m *MsgAdjustPlaneExperience) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAdjustPlaneExperience) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAdjustPlaneExperience.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAdjustPlaneExperience) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAdjustPlaneExperience.Merge(m, src)
}
func (m *MsgAdjustPlaneExperience) XXX_Size() int {
	return m.Size()
}
func (m *MsgAdjustPlaneExperience) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAdjustPlaneExperience.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAdjustPlaneExperience proto.InternalMessageInfo

func (m *MsgAdjustPlaneExperience) GetSupervisor() string {
	if m != nil {
		return m.Supervisor
	}
	return ""
}

func (m *MsgAdjustPlaneExperience) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MsgAdjustPlaneExperience) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type MsgAdjustPlaneExperienceResponse struct {
}

func (m *MsgAdjustPlaneExperienceResponse) Reset()         { *m = MsgAdjustPlaneExperienceResponse{} }
func (m *MsgAdjustPlaneExperienceResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAdjustPlaneExperienceResponse) ProtoMessage()    {}
func (*MsgAdjustPlaneExperienceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bfdcccde74665549, []int{7}
}
func (m *MsgAdjustPlaneExperienceResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAdjustPlaneExperienceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAdjustPlaneExperienceResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAdjustPlaneExperienceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAdjustPlaneExperienceResponse.Merge(m, src)
}
func (m *MsgAdjustPlaneExperienceResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAdjustPlaneExperienceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAdjustPlaneExperienceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAdjustPlaneExperienceResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PlaneMeta)(nil), "network.aviatrix.v1.PlaneMeta")
	proto.RegisterType((*Plane)(nil), "network.aviatrix.v1.Plane")
	proto.RegisterType((*MsgCreatePlane)(nil), "network.aviatrix.v1.MsgCreatePlane")
	proto.RegisterType((*MsgCreatePlaneResponse)(nil), "network.aviatrix.v1.MsgCreatePlaneResponse")
	proto.RegisterType((*MsgUpdatePlaneExperience)(nil), "network.aviatrix.v1.MsgUpdatePlaneExperience")
	proto.RegisterType((*MsgUpdatePlaneExperienceResponse)(nil), "network.aviatrix.v1.MsgUpdatePlaneExperienceResponse")
	proto.RegisterType((*MsgAdjustPlaneExperience)(nil), "network.aviatrix.v1.MsgAdjustPlaneExperience")
	proto.RegisterType((*MsgAdjustPlaneExperienceResponse)(nil), "network.aviatrix.v1.MsgAdjustPlaneExperienceResponse")
}

func init() { proto.RegisterFile("network/aviatrix/v1/tx.proto", fileDescriptor_bfdcccde74665549) }

var fileDescriptor_bfdcccde74665549 = []byte{
	// 428 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0xaa, 0xd3, 0x40,
	0x14, 0x86, 0x3b, 0x49, 0xef, 0x85, 0x7b, 0x0a, 0x15, 0xa2, 0xd6, 0x50, 0x64, 0x28, 0x71, 0x53,
	0x2c, 0x4d, 0x68, 0xc5, 0x8d, 0x3b, 0x15, 0x57, 0x12, 0x90, 0x80, 0x1b, 0x37, 0x32, 0x4d, 0x86,
	0x18, 0x35, 0x99, 0x30, 0x33, 0x49, 0xe3, 0xc2, 0x8d, 0x4f, 0xe0, 0xde, 0x97, 0xf0, 0x31, 0x5c,
	0x76, 0xe9, 0x52, 0x5a, 0xc1, 0xd7, 0x10, 0x93, 0xa6, 0x4d, 0xdb, 0x89, 0x56, 0xb8, 0xcb, 0x39,
	0xe7, 0xe7, 0xfc, 0xdf, 0x9c, 0x03, 0x3f, 0xdc, 0x4d, 0xa8, 0x5c, 0x32, 0xfe, 0xce, 0x21, 0x79,
	0x44, 0x24, 0x8f, 0x0a, 0x27, 0x9f, 0x39, 0xb2, 0xb0, 0x53, 0xce, 0x24, 0x33, 0x6e, 0x6e, 0xbb,
	0x76, 0xdd, 0xb5, 0xf3, 0xd9, 0xf0, 0x8e, 0xcf, 0x44, 0xcc, 0x84, 0x13, 0x8b, 0xf0, 0x8f, 0x38,
	0x16, 0x61, 0xa5, 0xb6, 0x26, 0x70, 0xf5, 0xe2, 0x3d, 0x49, 0xa8, 0x4b, 0x25, 0x31, 0x30, 0x00,
	0x2d, 0x52, 0xca, 0x23, 0x9a, 0xf8, 0xd4, 0xd4, 0x47, 0x68, 0xdc, 0xf5, 0x1a, 0x15, 0x8b, 0xc0,
	0x45, 0x29, 0x36, 0xfa, 0xa0, 0x45, 0x81, 0x89, 0x46, 0x68, 0x7c, 0xe5, 0x69, 0x51, 0x60, 0xdc,
	0x82, 0x0b, 0xb6, 0x4c, 0x28, 0x37, 0xb5, 0xb2, 0x54, 0x3d, 0x8c, 0x39, 0x74, 0x63, 0x2a, 0x49,
	0x39, 0xa8, 0x37, 0xc7, 0xb6, 0x02, 0xcc, 0xde, 0x99, 0x7b, 0xa5, 0xd6, 0xfa, 0x82, 0xa0, 0xef,
	0x8a, 0xf0, 0x29, 0xa7, 0x44, 0x52, 0xb5, 0x19, 0x06, 0x10, 0x59, 0x4a, 0x79, 0x1e, 0x09, 0x56,
	0x3b, 0x36, 0x2a, 0x7b, 0x18, 0x5d, 0x05, 0xd3, 0x3d, 0x1f, 0xe6, 0xd1, 0x8d, 0x4f, 0xbf, 0xbe,
	0xde, 0x6f, 0x8c, 0xb6, 0x4c, 0x18, 0x1c, 0xc2, 0x79, 0x54, 0xa4, 0x2c, 0x11, 0xd4, 0x12, 0x60,
	0xba, 0x22, 0x7c, 0x99, 0x06, 0x75, 0xe7, 0xd9, 0x6e, 0x6d, 0x47, 0xc0, 0xe8, 0x04, 0xb8, 0xfa,
	0xa0, 0xb6, 0xfb, 0xe0, 0x00, 0x2e, 0x49, 0xcc, 0xb2, 0x44, 0x6e, 0x4f, 0xb0, 0x7d, 0x9d, 0xe2,
	0x58, 0x30, 0x6a, 0x33, 0x3d, 0x02, 0x7b, 0x1c, 0xbc, 0xcd, 0x84, 0xbc, 0x5e, 0x30, 0xfd, 0x5f,
	0x60, 0x4a, 0xd3, 0x1a, 0x6c, 0xfe, 0x53, 0x03, 0xdd, 0x15, 0xa1, 0xf1, 0x1a, 0x7a, 0xcd, 0x6b,
	0xdf, 0x53, 0x5e, 0xe6, 0x70, 0xeb, 0xc3, 0xc9, 0x19, 0xa2, 0xda, 0xc8, 0xf8, 0x08, 0xb7, 0xd5,
	0x77, 0x99, 0xb6, 0x4d, 0x51, 0xca, 0x87, 0x0f, 0xff, 0x4b, 0xde, 0xb4, 0x57, 0x6f, 0xbf, 0xd5,
	0x5e, 0x29, 0x6f, 0xb7, 0xff, 0xeb, 0x9a, 0x9f, 0x3c, 0xff, 0xb6, 0xc6, 0x68, 0xb5, 0xc6, 0xe8,
	0xc7, 0x1a, 0xa3, 0xcf, 0x1b, 0xdc, 0x59, 0x6d, 0x70, 0xe7, 0xfb, 0x06, 0x77, 0x5e, 0xcd, 0xc2,
	0x48, 0xbe, 0xc9, 0x16, 0xb6, 0xcf, 0x62, 0x47, 0xf8, 0x8c, 0x67, 0xb1, 0x53, 0xa5, 0xc4, 0xb4,
	0xce, 0x97, 0x62, 0x9f, 0x30, 0xf2, 0x43, 0x4a, 0xc5, 0xe2, 0xb2, 0x0c, 0x8d, 0x07, 0xbf, 0x03,
	0x00, 0x00, 0xff, 0xff, 0x43, 0xb4, 0x2a, 0x4f, 0x82, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreatePlane(ctx context.Context, in *MsgCreatePlane, opts ...grpc.CallOption) (*MsgCreatePlaneResponse, error)
	UpdatePlaneExperience(ctx context.Context, in *MsgUpdatePlaneExperience, opts ...grpc.CallOption) (*MsgUpdatePlaneExperienceResponse, error)
	AdjustPlaneExperience(ctx context.Context, in *MsgAdjustPlaneExperience, opts ...grpc.CallOption) (*MsgAdjustPlaneExperienceResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreatePlane(ctx context.Context, in *MsgCreatePlane, opts ...grpc.CallOption) (*MsgCreatePlaneResponse, error) {
	out := new(MsgCreatePlaneResponse)
	err := c.cc.Invoke(ctx, "/network.aviatrix.v1.Msg/CreatePlane", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdatePlaneExperience(ctx context.Context, in *MsgUpdatePlaneExperience, opts ...grpc.CallOption) (*MsgUpdatePlaneExperienceResponse, error) {
	out := new(MsgUpdatePlaneExperienceResponse)
	err := c.cc.Invoke(ctx, "/network.aviatrix.v1.Msg/UpdatePlaneExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AdjustPlaneExperience(ctx context.Context, in *MsgAdjustPlaneExperience, opts ...grpc.CallOption) (*MsgAdjustPlaneExperienceResponse, error) {
	out := new(MsgAdjustPlaneExperienceResponse)
	err := c.cc.Invoke(ctx, "/network.aviatrix.v1.Msg/AdjustPlaneExperience", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreatePlane(context.Context, *MsgCreatePlane) (*MsgCreatePlaneResponse, error)
	UpdatePlaneExperience(context.Context, *MsgUpdatePlaneExperience) (*MsgUpdatePlaneExperienceResponse, error)
	AdjustPlaneExperience(context.Context, *MsgAdjustPlaneExperience) (*MsgAdjustPlaneExperienceResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreatePlane(ctx context.Context, req *MsgCreatePlane) (*MsgCreatePlaneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlane not implemented")
}
func (*UnimplementedMsgServer) UpdatePlaneExperience(ctx context.Context, req *MsgUpdatePlaneExperience) (*MsgUpdatePlaneExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlaneExperience not implemented")
}
func (*UnimplementedMsgServer) AdjustPlaneExperience(ctx context.Context, req *MsgAdjustPlaneExperience) (*MsgAdjustPlaneExperienceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdjustPlaneExperience not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreatePlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreatePlane)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreatePlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.aviatrix.v1.Msg/CreatePlane",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreatePlane(ctx, req.(*MsgCreatePlane))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdatePlaneExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdatePlaneExperience)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdatePlaneExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.aviatrix.v1.Msg/UpdatePlaneExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdatePlaneExperience(ctx, req.(*MsgUpdatePlaneExperience))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AdjustPlaneExperience_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAdjustPlaneExperience)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AdjustPlaneExperience(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/network.aviatrix.v1.Msg/AdjustPlaneExperience",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AdjustPlaneExperience(ctx, req.(*MsgAdjustPlaneExperience))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "network.aviatrix.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePlane",
			Handler:    _Msg_CreatePlane_Handler,
		},
		{
			MethodName: "UpdatePlaneExperience",
			Handler:    _Msg_UpdatePlaneExperience_Handler,
		},
		{
			MethodName: "AdjustPlaneExperience",
			Handler:    _Msg_AdjustPlaneExperience_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/aviatrix/v1/tx.proto",
}

func (m *PlaneMeta) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PlaneMeta) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PlaneMeta) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Experience != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Experience))
		i--
		dAtA[i] = 0x18
	}
	return len(dAtA) - i, nil
}

func (m *Plane) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Plane) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Plane) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Meta != nil {
		{
			size, err := m.Meta.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePlane) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePlane) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePlane) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Meta != nil {
		{
			size, err := m.Meta.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Supervisor) > 0 {
		i -= len(m.Supervisor)
		copy(dAtA[i:], m.Supervisor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Supervisor)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreatePlaneResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreatePlaneResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreatePlaneResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePlaneExperience) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePlaneExperience) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePlaneExperience) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Supervisor) > 0 {
		i -= len(m.Supervisor)
		copy(dAtA[i:], m.Supervisor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Supervisor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdatePlaneExperienceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdatePlaneExperienceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdatePlaneExperienceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgAdjustPlaneExperience) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAdjustPlaneExperience) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAdjustPlaneExperience) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Supervisor) > 0 {
		i -= len(m.Supervisor)
		copy(dAtA[i:], m.Supervisor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Supervisor)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAdjustPlaneExperienceResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAdjustPlaneExperienceResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAdjustPlaneExperienceResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PlaneMeta) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Experience != 0 {
		n += 1 + sovTx(uint64(m.Experience))
	}
	return n
}

func (m *Plane) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Meta != nil {
		l = m.Meta.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePlane) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Supervisor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Meta != nil {
		l = m.Meta.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreatePlaneResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdatePlaneExperience) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Supervisor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgUpdatePlaneExperienceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgAdjustPlaneExperience) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Supervisor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Amount != 0 {
		n += 1 + sovTx(uint64(m.Amount))
	}
	return n
}

func (m *MsgAdjustPlaneExperienceResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PlaneMeta) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PlaneMeta: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PlaneMeta: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Experience", wireType)
			}
			m.Experience = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Experience |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Plane) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Plane: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Plane: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Meta == nil {
				m.Meta = &PlaneMeta{}
			}
			if err := m.Meta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePlane) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePlane: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePlane: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supervisor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Supervisor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Meta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Meta == nil {
				m.Meta = &PlaneMeta{}
			}
			if err := m.Meta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreatePlaneResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreatePlaneResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreatePlaneResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePlaneExperience) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePlaneExperience: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePlaneExperience: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supervisor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Supervisor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdatePlaneExperienceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdatePlaneExperienceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdatePlaneExperienceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAdjustPlaneExperience) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAdjustPlaneExperience: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAdjustPlaneExperience: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supervisor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Supervisor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAdjustPlaneExperienceResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAdjustPlaneExperienceResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAdjustPlaneExperienceResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
