// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network/scorum/v1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	Supervisors            []string               `protobuf:"bytes,1,rep,name=supervisors,proto3" json:"supervisors,omitempty"`
	GasLimit               types.IntProto         `protobuf:"bytes,2,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit"`
	GasUnconditionedAmount types.IntProto         `protobuf:"bytes,3,opt,name=gas_unconditioned_amount,json=gasUnconditionedAmount,proto3" json:"gas_unconditioned_amount"`
	GasAdjustCoefficient   types.DecProto         `protobuf:"bytes,4,opt,name=gas_adjust_coefficient,json=gasAdjustCoefficient,proto3" json:"gas_adjust_coefficient"`
	ValidatorsReward       ValidatorsRewardParams `protobuf:"bytes,5,opt,name=validators_reward,json=validatorsReward,proto3" json:"validators_reward"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_bce858b8f0dc09a2, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetSupervisors() []string {
	if m != nil {
		return m.Supervisors
	}
	return nil
}

func (m *Params) GetGasLimit() types.IntProto {
	if m != nil {
		return m.GasLimit
	}
	return types.IntProto{}
}

func (m *Params) GetGasUnconditionedAmount() types.IntProto {
	if m != nil {
		return m.GasUnconditionedAmount
	}
	return types.IntProto{}
}

func (m *Params) GetGasAdjustCoefficient() types.DecProto {
	if m != nil {
		return m.GasAdjustCoefficient
	}
	return types.DecProto{}
}

func (m *Params) GetValidatorsReward() ValidatorsRewardParams {
	if m != nil {
		return m.ValidatorsReward
	}
	return ValidatorsRewardParams{}
}

type ValidatorsRewardParams struct {
	PoolAddress string     `protobuf:"bytes,1,opt,name=pool_address,json=poolAddress,proto3" json:"pool_address,omitempty"`
	BlockReward types.Coin `protobuf:"bytes,2,opt,name=block_reward,json=blockReward,proto3" json:"block_reward"`
}

func (m *ValidatorsRewardParams) Reset()         { *m = ValidatorsRewardParams{} }
func (m *ValidatorsRewardParams) String() string { return proto.CompactTextString(m) }
func (*ValidatorsRewardParams) ProtoMessage()    {}
func (*ValidatorsRewardParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_bce858b8f0dc09a2, []int{1}
}
func (m *ValidatorsRewardParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ValidatorsRewardParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ValidatorsRewardParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ValidatorsRewardParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ValidatorsRewardParams.Merge(m, src)
}
func (m *ValidatorsRewardParams) XXX_Size() int {
	return m.Size()
}
func (m *ValidatorsRewardParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ValidatorsRewardParams.DiscardUnknown(m)
}

var xxx_messageInfo_ValidatorsRewardParams proto.InternalMessageInfo

func (m *ValidatorsRewardParams) GetPoolAddress() string {
	if m != nil {
		return m.PoolAddress
	}
	return ""
}

func (m *ValidatorsRewardParams) GetBlockReward() types.Coin {
	if m != nil {
		return m.BlockReward
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Params)(nil), "network.scorum.v1.Params")
	proto.RegisterType((*ValidatorsRewardParams)(nil), "network.scorum.v1.ValidatorsRewardParams")
}

func init() { proto.RegisterFile("network/scorum/v1/params.proto", fileDescriptor_bce858b8f0dc09a2) }

var fileDescriptor_bce858b8f0dc09a2 = []byte{
	// 429 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xb1, 0x6f, 0xd3, 0x40,
	0x14, 0xc6, 0x6d, 0x12, 0x2a, 0x7a, 0xe9, 0x40, 0xad, 0xaa, 0x32, 0x95, 0x70, 0x43, 0xa7, 0x32,
	0x70, 0xa7, 0xc0, 0xc6, 0x44, 0x52, 0x96, 0x4a, 0x0c, 0x55, 0x24, 0x90, 0x40, 0x20, 0xeb, 0x7c,
	0xbe, 0x9a, 0xa3, 0xf1, 0x3d, 0xeb, 0xde, 0xd9, 0x85, 0x89, 0x9d, 0x89, 0x91, 0x91, 0x3f, 0xa7,
	0x63, 0x47, 0x26, 0x84, 0x92, 0x7f, 0x04, 0xdd, 0x5d, 0x02, 0x11, 0x44, 0x88, 0xcd, 0x7a, 0xdf,
	0x7b, 0xbf, 0xef, 0xf9, 0xbe, 0x47, 0x32, 0x2d, 0xed, 0x25, 0x98, 0x0b, 0x86, 0x02, 0x4c, 0x5b,
	0xb3, 0x6e, 0xc4, 0x1a, 0x6e, 0x78, 0x8d, 0xb4, 0x31, 0x60, 0x21, 0xd9, 0x5d, 0xea, 0x34, 0xe8,
	0xb4, 0x1b, 0x1d, 0xec, 0x55, 0x50, 0x81, 0x57, 0x99, 0xfb, 0x0a, 0x8d, 0x07, 0x99, 0x00, 0xac,
	0x01, 0x59, 0xc1, 0x51, 0xb2, 0x6e, 0x54, 0x48, 0xcb, 0x47, 0x4c, 0x80, 0xd2, 0x41, 0x3f, 0xfa,
	0xd4, 0x23, 0x5b, 0x67, 0x9e, 0x9c, 0x0c, 0xc9, 0x00, 0xdb, 0x46, 0x9a, 0x4e, 0x21, 0x18, 0x4c,
	0xe3, 0x61, 0xef, 0x78, 0x7b, 0xba, 0x5e, 0x4a, 0x9e, 0x90, 0xed, 0x8a, 0x63, 0x3e, 0x53, 0xb5,
	0xb2, 0xe9, 0x8d, 0x61, 0x7c, 0x3c, 0x78, 0x78, 0x97, 0x06, 0x03, 0xea, 0x0c, 0xe8, 0xd2, 0x80,
	0x9e, 0x6a, 0x7b, 0xe6, 0xf0, 0x93, 0xfe, 0xd5, 0xf7, 0xc3, 0x68, 0x7a, 0xab, 0xe2, 0xf8, 0xcc,
	0x0d, 0x25, 0x6f, 0x48, 0xea, 0x08, 0xad, 0x16, 0xa0, 0x4b, 0x65, 0x15, 0x68, 0x59, 0xe6, 0xbc,
	0x86, 0x56, 0xdb, 0xb4, 0xf7, 0xff, 0xc0, 0xfd, 0x8a, 0xe3, 0xf3, 0x75, 0xc6, 0xd8, 0x23, 0x92,
	0x97, 0xc4, 0x29, 0x39, 0x2f, 0xdf, 0xb5, 0x68, 0x73, 0x01, 0xf2, 0xfc, 0x5c, 0x09, 0x25, 0xb5,
	0x4d, 0xfb, 0xff, 0x80, 0x3f, 0x95, 0x62, 0x1d, 0xbe, 0x57, 0x71, 0x1c, 0x7b, 0xc2, 0xc9, 0x6f,
	0x40, 0xf2, 0x9a, 0xec, 0x76, 0x7c, 0xa6, 0x4a, 0x6e, 0xc1, 0x60, 0x6e, 0xe4, 0x25, 0x37, 0x65,
	0x7a, 0xd3, 0x53, 0xef, 0xd3, 0xbf, 0xd2, 0xa0, 0x2f, 0x7e, 0xf5, 0x4e, 0x7d, 0x6b, 0x78, 0xe3,
	0xa5, 0xc3, 0xed, 0xee, 0x0f, 0xf5, 0x71, 0xff, 0xcb, 0xd7, 0xc3, 0xe8, 0xe8, 0x23, 0xd9, 0xdf,
	0x3c, 0x97, 0xdc, 0x23, 0x3b, 0x0d, 0xc0, 0x2c, 0xe7, 0x65, 0x69, 0x24, 0xba, 0x70, 0x62, 0x17,
	0x8e, 0xab, 0x8d, 0x43, 0x29, 0x99, 0x90, 0x9d, 0x62, 0x06, 0xe2, 0x62, 0xb5, 0x5b, 0xc8, 0xe7,
	0xce, 0xc6, 0x3f, 0x3e, 0x01, 0xa5, 0x97, 0xbb, 0x0c, 0xfc, 0x50, 0x30, 0x9b, 0x9c, 0x5e, 0xcd,
	0xb3, 0xf8, 0x7a, 0x9e, 0xc5, 0x3f, 0xe6, 0x59, 0xfc, 0x79, 0x91, 0x45, 0xd7, 0x8b, 0x2c, 0xfa,
	0xb6, 0xc8, 0xa2, 0x57, 0xac, 0x52, 0xf6, 0x6d, 0x5b, 0x50, 0x01, 0xf5, 0xea, 0x26, 0x03, 0xf8,
	0xc1, 0xea, 0x52, 0xdf, 0xaf, 0xea, 0xf6, 0x43, 0x23, 0xb1, 0xd8, 0xf2, 0xf7, 0xf5, 0xe8, 0x67,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0xbf, 0x06, 0x11, 0xca, 0x02, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.ValidatorsReward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size, err := m.GasAdjustCoefficient.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size, err := m.GasUnconditionedAmount.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size, err := m.GasLimit.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Supervisors) > 0 {
		for iNdEx := len(m.Supervisors) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Supervisors[iNdEx])
			copy(dAtA[i:], m.Supervisors[iNdEx])
			i = encodeVarintParams(dAtA, i, uint64(len(m.Supervisors[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ValidatorsRewardParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ValidatorsRewardParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ValidatorsRewardParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BlockReward.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.PoolAddress) > 0 {
		i -= len(m.PoolAddress)
		copy(dAtA[i:], m.PoolAddress)
		i = encodeVarintParams(dAtA, i, uint64(len(m.PoolAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Supervisors) > 0 {
		for _, s := range m.Supervisors {
			l = len(s)
			n += 1 + l + sovParams(uint64(l))
		}
	}
	l = m.GasLimit.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.GasUnconditionedAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.GasAdjustCoefficient.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.ValidatorsReward.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func (m *ValidatorsRewardParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolAddress)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	l = m.BlockReward.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Supervisors", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Supervisors = append(m.Supervisors, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasLimit", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasLimit.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasUnconditionedAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasUnconditionedAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GasAdjustCoefficient", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.GasAdjustCoefficient.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorsReward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ValidatorsReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ValidatorsRewardParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ValidatorsRewardParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ValidatorsRewardParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockReward", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BlockReward.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
