// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: network/scorum/v1/types.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SPWithdrawal struct {
	Id                      string                `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                    string                `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To                      string                `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Total                   cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=total,proto3,customtype=cosmossdk.io/math.Int" json:"total"`
	PeriodDurationInSeconds uint32                `protobuf:"varint,5,opt,name=period_duration_in_seconds,json=periodDurationInSeconds,proto3" json:"period_duration_in_seconds,omitempty"`
	TotalPeriods            uint32                `protobuf:"varint,6,opt,name=total_periods,json=totalPeriods,proto3" json:"total_periods,omitempty"`
	ProcessedPeriod         uint32                `protobuf:"varint,7,opt,name=processed_period,json=processedPeriod,proto3" json:"processed_period,omitempty"`
	IsActive                bool                  `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt               uint64                `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (m *SPWithdrawal) Reset()         { *m = SPWithdrawal{} }
func (m *SPWithdrawal) String() string { return proto.CompactTextString(m) }
func (*SPWithdrawal) ProtoMessage()    {}
func (*SPWithdrawal) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cd9d06b742befe6, []int{0}
}
func (m *SPWithdrawal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SPWithdrawal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SPWithdrawal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SPWithdrawal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SPWithdrawal.Merge(m, src)
}
func (m *SPWithdrawal) XXX_Size() int {
	return m.Size()
}
func (m *SPWithdrawal) XXX_DiscardUnknown() {
	xxx_messageInfo_SPWithdrawal.DiscardUnknown(m)
}

var xxx_messageInfo_SPWithdrawal proto.InternalMessageInfo

func (m *SPWithdrawal) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SPWithdrawal) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SPWithdrawal) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *SPWithdrawal) GetPeriodDurationInSeconds() uint32 {
	if m != nil {
		return m.PeriodDurationInSeconds
	}
	return 0
}

func (m *SPWithdrawal) GetTotalPeriods() uint32 {
	if m != nil {
		return m.TotalPeriods
	}
	return 0
}

func (m *SPWithdrawal) GetProcessedPeriod() uint32 {
	if m != nil {
		return m.ProcessedPeriod
	}
	return 0
}

func (m *SPWithdrawal) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *SPWithdrawal) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*SPWithdrawal)(nil), "network.scorum.v1.SPWithdrawal")
}

func init() { proto.RegisterFile("network/scorum/v1/types.proto", fileDescriptor_4cd9d06b742befe6) }

var fileDescriptor_4cd9d06b742befe6 = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x92, 0x31, 0x6f, 0x13, 0x31,
	0x14, 0xc7, 0xe3, 0x90, 0x96, 0xc4, 0x4a, 0x81, 0x5a, 0x20, 0x4c, 0x50, 0xaf, 0x27, 0x58, 0x0e,
	0xa4, 0x9e, 0x89, 0x18, 0x99, 0x5a, 0x21, 0xa4, 0x6c, 0xd5, 0x75, 0x40, 0x62, 0x39, 0x39, 0xb6,
	0x49, 0xac, 0xf6, 0xfc, 0x22, 0xfb, 0x25, 0x85, 0x6f, 0xc1, 0xc7, 0x60, 0x64, 0xe0, 0x43, 0x74,
	0xac, 0x60, 0x41, 0x0c, 0x15, 0x4a, 0x06, 0xbe, 0x06, 0xaa, 0x7d, 0x61, 0x39, 0xbd, 0xf7, 0xfb,
	0xff, 0xce, 0xb6, 0xec, 0x47, 0x0f, 0x9c, 0xc1, 0x4b, 0xf0, 0xe7, 0x22, 0x28, 0xf0, 0xcb, 0x46,
	0xac, 0xc6, 0x02, 0x3f, 0x2f, 0x4c, 0x28, 0x17, 0x1e, 0x10, 0xd8, 0x7e, 0x1b, 0x97, 0x29, 0x2e,
	0x57, 0xe3, 0xd1, 0xc3, 0x19, 0xcc, 0x20, 0xa6, 0xe2, 0xb6, 0x4a, 0xe2, 0x68, 0x5f, 0x36, 0xd6,
	0x81, 0x88, 0xdf, 0x16, 0x3d, 0x51, 0x10, 0x1a, 0x08, 0x75, 0x72, 0x53, 0xd3, 0x46, 0x59, 0xea,
	0xc4, 0x54, 0x06, 0x23, 0x56, 0xe3, 0xa9, 0x41, 0x39, 0x16, 0x0a, 0xac, 0x4b, 0xf9, 0xb3, 0x9f,
	0x5d, 0x3a, 0x3c, 0x3b, 0x7d, 0x6f, 0x71, 0xae, 0xbd, 0xbc, 0x94, 0x17, 0xec, 0x1e, 0xed, 0x5a,
	0xcd, 0x49, 0x4e, 0x8a, 0x41, 0xd5, 0xb5, 0x9a, 0x31, 0xda, 0xfb, 0xe8, 0xa1, 0xe1, 0xdd, 0x48,
	0x62, 0x7d, 0xeb, 0x20, 0xf0, 0x3b, 0xc9, 0x41, 0x60, 0xef, 0xe8, 0x0e, 0x02, 0xca, 0x0b, 0xde,
	0xcb, 0x49, 0x31, 0x3c, 0x79, 0x75, 0x75, 0x73, 0xd8, 0xf9, 0x7d, 0x73, 0xf8, 0x28, 0xed, 0x1d,
	0xf4, 0x79, 0x69, 0x41, 0x34, 0x12, 0xe7, 0xe5, 0xc4, 0xe1, 0x8f, 0xef, 0x47, 0xb4, 0x3d, 0xe2,
	0xc4, 0xe1, 0xd7, 0xbf, 0xdf, 0x5e, 0x92, 0x2a, 0xfd, 0xce, 0xde, 0xd0, 0xd1, 0xc2, 0x78, 0x0b,
	0xba, 0xd6, 0x4b, 0x2f, 0xd1, 0x82, 0xab, 0xad, 0xab, 0x83, 0x51, 0xe0, 0x74, 0xe0, 0x3b, 0x39,
	0x29, 0xf6, 0xaa, 0xc7, 0xc9, 0x78, 0xdb, 0x0a, 0x13, 0x77, 0x96, 0x62, 0xf6, 0x9c, 0xee, 0xc5,
	0x55, 0xea, 0x24, 0x04, 0xbe, 0x1b, 0xfd, 0x61, 0x84, 0xa7, 0x89, 0xb1, 0x17, 0xf4, 0xc1, 0xc2,
	0x83, 0x32, 0x21, 0x18, 0xdd, 0x8a, 0xfc, 0x6e, 0xf4, 0xee, 0xff, 0xe7, 0xc9, 0x65, 0x4f, 0xe9,
	0xc0, 0x86, 0x5a, 0x2a, 0xb4, 0x2b, 0xc3, 0xfb, 0x39, 0x29, 0xfa, 0x55, 0xdf, 0x86, 0xe3, 0xd8,
	0xb3, 0x03, 0x4a, 0x95, 0x37, 0x12, 0x8d, 0xae, 0x25, 0xf2, 0x41, 0x4e, 0x8a, 0x5e, 0x35, 0x68,
	0xc9, 0x31, 0x9e, 0x4c, 0xae, 0xd6, 0x19, 0xb9, 0x5e, 0x67, 0xe4, 0xcf, 0x3a, 0x23, 0x5f, 0x36,
	0x59, 0xe7, 0x7a, 0x93, 0x75, 0x7e, 0x6d, 0xb2, 0xce, 0x07, 0x31, 0xb3, 0x38, 0x5f, 0x4e, 0x4b,
	0x05, 0xcd, 0x76, 0x10, 0xd2, 0x65, 0x1c, 0x6d, 0xc7, 0xe3, 0xd3, 0x96, 0xc7, 0xe9, 0x98, 0xee,
	0xc6, 0x77, 0x7a, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x26, 0x9f, 0x6d, 0x33, 0x3f, 0x02, 0x00,
	0x00,
}

func (m *SPWithdrawal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SPWithdrawal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SPWithdrawal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreatedAt != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.CreatedAt))
		i--
		dAtA[i] = 0x48
	}
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.ProcessedPeriod != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.ProcessedPeriod))
		i--
		dAtA[i] = 0x38
	}
	if m.TotalPeriods != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.TotalPeriods))
		i--
		dAtA[i] = 0x30
	}
	if m.PeriodDurationInSeconds != 0 {
		i = encodeVarintTypes(dAtA, i, uint64(m.PeriodDurationInSeconds))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Total.Size()
		i -= size
		if _, err := m.Total.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTypes(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.To) > 0 {
		i -= len(m.To)
		copy(dAtA[i:], m.To)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.To)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.From) > 0 {
		i -= len(m.From)
		copy(dAtA[i:], m.From)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.From)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintTypes(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTypes(dAtA []byte, offset int, v uint64) int {
	offset -= sovTypes(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SPWithdrawal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.From)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = len(m.To)
	if l > 0 {
		n += 1 + l + sovTypes(uint64(l))
	}
	l = m.Total.Size()
	n += 1 + l + sovTypes(uint64(l))
	if m.PeriodDurationInSeconds != 0 {
		n += 1 + sovTypes(uint64(m.PeriodDurationInSeconds))
	}
	if m.TotalPeriods != 0 {
		n += 1 + sovTypes(uint64(m.TotalPeriods))
	}
	if m.ProcessedPeriod != 0 {
		n += 1 + sovTypes(uint64(m.ProcessedPeriod))
	}
	if m.IsActive {
		n += 2
	}
	if m.CreatedAt != 0 {
		n += 1 + sovTypes(uint64(m.CreatedAt))
	}
	return n
}

func sovTypes(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTypes(x uint64) (n int) {
	return sovTypes(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SPWithdrawal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SPWithdrawal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SPWithdrawal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field From", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.From = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field To", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.To = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Total", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthTypes
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthTypes
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Total.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PeriodDurationInSeconds", wireType)
			}
			m.PeriodDurationInSeconds = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PeriodDurationInSeconds |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalPeriods", wireType)
			}
			m.TotalPeriods = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalPeriods |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProcessedPeriod", wireType)
			}
			m.ProcessedPeriod = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ProcessedPeriod |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			m.CreatedAt = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreatedAt |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTypes(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTypes
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTypes(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTypes
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTypes
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTypes
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTypes
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTypes
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTypes        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTypes          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTypes = fmt.Errorf("proto: unexpected end of group")
)
