name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Run linter
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.22
        id: go

      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Test
        run: make test

      - name: Lint
        run: make install-linter && make lint
