name: main

on:
  push:
    tags:
      - 'v*'

jobs:
  build-image:
    name: build image
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: log in to docker hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with: # todo: change to group secrets on making repo public
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: extract metadata for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: scorum/cosmos-network

      - name: build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
